// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: sro/gamedata/gamedata.proto

package pb

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// GameDataServiceClient is the client API for GameDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameDataServiceClient interface {
}

type gameDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameDataServiceClient(cc grpc.ClientConnInterface) GameDataServiceClient {
	return &gameDataServiceClient{cc}
}

// GameDataServiceServer is the server API for GameDataService service.
// All implementations must embed UnimplementedGameDataServiceServer
// for forward compatibility.
type GameDataServiceServer interface {
	mustEmbedUnimplementedGameDataServiceServer()
}

// UnimplementedGameDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameDataServiceServer struct{}

func (UnimplementedGameDataServiceServer) mustEmbedUnimplementedGameDataServiceServer() {}
func (UnimplementedGameDataServiceServer) testEmbeddedByValue()                         {}

// UnsafeGameDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameDataServiceServer will
// result in compilation errors.
type UnsafeGameDataServiceServer interface {
	mustEmbedUnimplementedGameDataServiceServer()
}

func RegisterGameDataServiceServer(s grpc.ServiceRegistrar, srv GameDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameDataService_ServiceDesc, srv)
}

// GameDataService_ServiceDesc is the grpc.ServiceDesc for GameDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sro.gamedata.GameDataService",
	HandlerType: (*GameDataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "sro/gamedata/gamedata.proto",
}
